### ISSUE TITLE
Travis CI config to deploy snapshots and releases to Sonatype

### ISSUE THREAD

**Issue by iantmoore** [G2G3Digital/substeps-framework#7]
see http://central.sonatype.org/pages/apache-maven.html

**Comment by beercanx** [comment]
Was thinking that to be able to do Travis-CI we would have to upgrade to at least Java 7 due to JDK available, but I think by setting the source and target to 1.6 and using the animal-sniffer-maven-plugin to enforce Java API usage. 

We maybe able to get away without upgrading the Java version, of course I'll test this out before pushing snapshots out.

**Comment by iantmoore** [comment]
as I recall, the 1.5 compatibility was enforced by a particular legacy project using Substeps.  version 2.0 might be a reasonable point to dictate 1.7+.. ?  Even if the project in question requires  a legacy JVM, the tests could run with a different version..  seems reasonable enough to me...

**Comment by beercanx** [comment]
So for now we have Travis CI deploying snapshots on all builds, except pull requests.

I shall be working on handling the release stuff in Travis CI later.

**Comment by beercanx** [comment]
So the final hurdle we reach...

Currently mulling over the release branch vs tagging to trigger releases and auto upload artifacts to github or maybe a mixture will work.
- **GitHub Artifact Uploading** https://docs.travis-ci.com/user/deployment/releases
- **A way to handle the GPG signing on Travis** https://www.theguardian.com/info/developer-blog/2014/sep/16/shipping-from-github-to-maven-central-and-s3-using-travis-ci

Current thought maybe to:
- Until we get it working 100% releases will not automatically release artifacts from the Sonatype staging area.
- Perform a maven release only when building the "release" branch.
- Enable Travis to push back into github, which enables us to use vanilla maven release processes
- Utilise the deploy phase in Travis to upload artifacts to the tag in a separate build that would be triggered once the maven release is performed.

But shall mull these thoughts over before acting further.

Have currently set us a goal of getting this sorted by the 4th December with no more changes planned to be included.

**Comment by beercanx** [comment]
A maven badge we can add to the read me, thanks to @iantmoore for that.

Downside is we can't link directly to the maven central entry as we have multiple artifacts in substeps-framework. So I thought to just list all packages under the group id com.technophobia.substeps

substeps-framework
[![Maven Central](https://img.shields.io/maven-central/v/com.technophobia.substeps/substeps-framework.svg)](http://search.maven.org/#search%7Cga%7C1%7Cg%3Acom.technophobia.substeps)

substeps-core-api
[![Maven Central](https://img.shields.io/maven-central/v/com.technophobia.substeps/substeps-core-api.svg)](http://search.maven.org/#search%7Cga%7C1%7Cg%3Acom.technophobia.substeps)

Sources
- http://shields.io
- https://github.com/jirutka/maven-badges

**Comment by iantmoore** [comment]
nice!

**Comment by beercanx** [comment]
Have changed some of the current Travis config on master to use deploys and conditions to only run on the G2G3D repo.

I'm hoping the snapshots still deploy and that I haven't broken Travis, seems a little sluggish to detect changes currently.

Also added a test for uploading to a GitHub Release tag, which currently relies on snapshots but will be changed for release only artifacts.

**Comment by beercanx** [comment]
Relevant changes and configurations has been made to release from Travis-CI.

All that is left is for the manual release of the staged release code, this I can do on Tuesday.
